# Generated by Django 5.2.15 on 2026-06-07 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productvariant_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم المحافظة')),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الشحن للمحافظة')),
            ],
            options={
                'verbose_name': 'محافظة وشحن',
                'verbose_name_plural': 'إدارة المحافظات والشحن',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='اسم العميل (ضروري)')),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم الهاتف (عليه واتساب)')),
                ('alternate_phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم هاتف إضافي (اختياري)')),
                ('shipping_price_at_order', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='تمن الشحن وقت الطلب')),
                ('address_details', models.TextField(verbose_name='العنوان بالتفصيل')),
                ('total_products_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='إجمالي سعر الساعات')),
                ('final_total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الإجمالي (بالشحن)')),
                ('status', models.CharField(choices=[('Pending', 'قيد المراجعة'), ('Shipped', 'تم الشحن'), ('Completed', 'تم التوصيل بنجاح'), ('Cancelled', 'ملغي')], default='Pending', max_length=20, verbose_name='حالة الطلب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ ووقت الطلب')),
                ('governorate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.governorate', verbose_name='المحافظة')),
            ],
            options={
                'verbose_name': 'طلب عميل',
                'verbose_name_plural': 'الطلبات والاوردرات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=255, verbose_name='اسم الساعة وقت الشراء')),
                ('color_name', models.CharField(max_length=50, verbose_name='اللون المحدد')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية المطلوبة')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر القطعة وقت الشراء')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.order', verbose_name='الطلب التابع له')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product', verbose_name='الساعة')),
            ],
            options={
                'verbose_name': 'قطعة داخل الطلب',
                'verbose_name_plural': 'تفاصيل القطع المطلوبة',
            },
        ),
    ]
