# Generated by Django 5.2.15 on 2026-06-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_governorate_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'قيد المراجعة'), ('Completed', 'تم التوصيل بنجاح'), ('Cancelled', 'ملغي')], default='Pending', max_length=20, verbose_name='حالة الطلب'),
        ),
    ]
