# Generated by Django 5.2.15 on 2026-06-10 04:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_discount_percentage',
            field=models.PositiveIntegerField(default=0, help_text='نسبة الخصم الخاصة بالعرض، تُطبَّق على السعر الأصلي مباشرةً وليس على سعر الخصم الدائم', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة خصم العرض المحدود (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ ووقت انتهاء العرض'),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ ووقت بدء العرض'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الخصم الدائم (%)'),
        ),
    ]
